#!/bin/sh

FLASKR_PID_FILE="/var/run/flaskr.pid"

# Source function library.
. /etc/init.d/functions

RETVAL=0

case "$1" in
    start)
	echo -n "Starting Flaskr "
	daemon python /srv/flaskr/flaskr.py --pidfile "$FLASKR_PID_FILE" > /dev/null
	RETVAL=$?
	if [ $RETVAL = 0 ]; then
	    success
	else
	    failure
	fi
	echo
	;;
    stop)
	echo -n "Shutting down Flaskr "
	killproc flaskr
	RETVAL=$?
	echo
	;;
    restart)
	$0 stop
	$0 start
	;;
    status)
    	status flaskr
	RETVAL=$?
	;;
    *)
	echo "Usage: $0 {start|stop|restart|status}"
	exit 1
	;;
esac
exit $RETVAL
