#!/bin/sh

### BEGIN INIT INFO
# Provides:          flaskr
# Required-Start:    $local_fs $network
# Required-Stop:     $local_fs $network
# Default-Start:     3 5
# Default-Stop:      0 1 2 6
# Short-Description: Flaskr (Devops class flavored)
# Description:       Flaskr (Devops class flavored)
### END INIT INFO

FLASKR_PID_FILE="/var/run/flaskr.pid"

# Source function library.
. /etc/init.d/functions

RETVAL=0

case "$1" in
    start)
	echo -n "Starting Flaskr "
	nohup python /srv/flaskr/flaskr.py --pidfile "$FLASKR_PID_FILE" > /tmp/flaskr.log 2>&1 &
	RETVAL=$?
	if [ $RETVAL = 0 ]; then
	    success
	else
	    failure
	fi
	echo
	;;
    stop)
	echo -n "Shutting down Flaskr "
	kill $(cat "$FLASKR_PID_FILE")
	RETVAL=$?
	echo
	;;
    restart)
	$0 stop
	$0 start
	;;
    status)
    	status flaskr
	RETVAL=$?
	;;
    *)
	echo "Usage: $0 {start|stop|restart|status}"
	exit 1
	;;
esac
exit $RETVAL
